In [45]:
import pandas as pd # pandas package
import numpy as np # numpy package
import statistics as st # statistics package

In [48]:
sleep = pd.read_csv('studentlife_sleep.csv') # insert clean dataset
sleep

     uid  entry index  hour  rate  sleep interference  cs65_gpa
0    u02            1     8     2                   1       4.0
1    u02            2     7     3                   1       4.0
2    u02            3     8     2                   1       4.0
3    u02            4     7     2                   1       4.0
4    u02            5     8     2                   1       4.0
..   ...          ...   ...   ...                 ...       ...
939  u52           19     9     1                   1       0.0
940  u52           20     9     2                   1       0.0
941  u52           21     7     1                   2       0.0
942  u52           22     9     2                   1       0.0
943  u52           23     1     2                   1       0.0

[944 rows x 6 columns]

In [49]:
print("Shape of dataset",sleep.shape) # shape of dataset

Shape of dataset (944, 6)

In [50]:
sleep.head() # show first 5 rows

   uid  entry index  hour  rate  sleep interference  cs65_gpa
0  u02            1     8     2                   1       4.0
1  u02            2     7     3                   1       4.0
2  u02            3     8     2                   1       4.0
3  u02            4     7     2                   1       4.0
4  u02            5     8     2                   1       4.0

In [51]:
std_dev_hours = st.stdev(sleep['hour']) # create standard deviation of sleep hours
sleep['stdev_hours'] = std_dev_hours # save values as a new column
sleep.head() # show first 5 rows for evidence

   uid  entry index  hour  rate  sleep interference  cs65_gpa  stdev_hours
0  u02            1     8     2                   1       4.0     2.417456
1  u02            2     7     3                   1       4.0     2.417456
2  u02            3     8     2                   1       4.0     2.417456
3  u02            4     7     2                   1       4.0     2.417456
4  u02            5     8     2                   1       4.0     2.417456

In [52]:
sleep = sleep.drop("uid",axis=1) # drop id column
sleep.head() # show first 5 rows for evidence

   entry index  hour  rate  sleep interference  cs65_gpa  stdev_hours
0            1     8     2                   1       4.0     2.417456
1            2     7     3                   1       4.0     2.417456
2            3     8     2                   1       4.0     2.417456
3            4     7     2                   1       4.0     2.417456
4            5     8     2                   1       4.0     2.417456

In [53]:
sleep.columns.tolist() # list all available column names, to copy-paste as my x features

['entry index',
 'hour',
 'rate',
 'sleep interference',
 'cs65_gpa',
 'stdev_hours']

In [54]:
from sklearn.model_selection import train_test_split # train-test split package

x_col = ['entry index',
 'hour',
 'rate',
 'sleep interference',
 'stdev_hours'] # feature columns

y_col = ['cs65_gpa'] # target column

X, y = sleep[x_col], sleep[y_col] # setting X and y as the respective columns

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=10272025) # standard train/test split initialization

In [55]:
sleep.head()

   entry index  hour  rate  sleep interference  cs65_gpa  stdev_hours
0            1     8     2                   1       4.0     2.417456
1            2     7     3                   1       4.0     2.417456
2            3     8     2                   1       4.0     2.417456
3            4     7     2                   1       4.0     2.417456
4            5     8     2                   1       4.0     2.417456